### ISSUE TITLE
Issue: The palbot user with sudo access

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [dkoz/palworld-palbot#10]
Hey guys! 

The guide recommends using sudo for installation and running the bot. I certainly wouldn't want to provide it superuser access on my machine. Is the reason for it is the env creation? Shouldn't it be better to create the env first with a superuser and just execute palbot without sudo?

Thanks. 

Linux/Bash/Standalone

**Comment by dkoz** [comment]
> Hey guys!
> 
> The guide recommends using sudo for installation and running the bot. I certainly wouldn't want to provide it superuser access on my machine. Is the reason for it is the env creation? Shouldn't it be better to create the env first with a superuser and just execute palbot without sudo?
> 
> Thanks.
> 
> Linux/Bash/Standalone

The guide is written in a way to provide the user with an easy way to setup the bot on a VPS or bare metal machine. While I understand the concerns of providing a new user that kind of access, most people will have a difficult time without it. You can also just run it through docker which would be a lot easier.
