### ISSUE TITLE
Economy System for Xbox

### ISSUE THREAD

**Issue by FellipeSuke** [dkoz/palworld-palbot#11]
Automatic assignment of Xbox accounts in Discord to characters on the dedicated server

Currently, it is not possible to automatically assign the relationship between the Discord user and the character/account on the dedicated server for the Xbox platform. This process can only be done manually.

I would like to know if it's possible to implement a feature where users with Xbox links in their Discord account can be automatically assigned to the game, ensuring the in-game economy functions properly.

Steps to reproduce:

Try to automatically link a Discord user's account with an Xbox link to their character on the dedicated server.
Notice that the relationship needs to be manually assigned.
Expected result: Users with an Xbox link in Discord should be automatically assigned to the game, making integration smoother and allowing the in-game economy to function properly.

Current result: The relationship between the Discord account and the character on the server must be assigned manually.
Is it in the plans to integrate with Xbox? Can you help us with this?

**Comment by dkoz** [comment]
The only known way to get an Xbox ID is from the person being on the server. When you look at the `showplayers` output from RCON, it should say `gdk_1234567`. The ID displayed after `gdk_` would be used to link their account to the bot. 

That being said, Palguard does work with Xbox IDs so there should be no issues just using the `/setsteam` command with the Xbox ID instead. You can also use the `/economyset forcesteam` command to set the ID for them.
