### ISSUE TITLE
linux docker setup

### ISSUE THREAD

**Issue by iceyman** [dkoz/palworld-palbot#5]
on debain or ubuntu i innstalled bot but keeps restarting in logs i get 

palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  | Palguard disabled by default. Please enable it in config.json
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 774, in _load_from_module_spec
palbot_1  |     setup(self, **extras)
palbot_1  |   File "/app/cogs/economy/shop.py", line 189, in setup
palbot_1  |     bot.add_cog(ShopCog(bot))
palbot_1  |                 ^^^^^^^^^^^^
palbot_1  |   File "/app/cogs/economy/shop.py", line 61, in __init__
palbot_1  |     self.load_shop_items()
palbot_1  |   File "/app/cogs/economy/shop.py", line 82, in load_shop_items
palbot_1  |     with open(shop_items_path) as shop_items_file:
palbot_1  |          ^^^^^^^^^^^^^^^^^^^^^
palbot_1  | FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'
palbot_1  |
palbot_1  | The above exception was the direct cause of the following exception:
palbot_1  |
palbot_1  | Traceback (most recent call last):
palbot_1  |   File "/app/main.py", line 69, in <module>
palbot_1  |     bot.load_extension(module_name)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 862, in load_extension
palbot_1  |     self._load_from_module_spec(spec, name, extras=extras)
palbot_1  |   File "/usr/local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 779, in _load_from_module_spec
palbot_1  |     raise errors.ExtensionFailed(key, e) from e
palbot_1  | nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.economy.shop' raised an error: FileNotFoundError: [Errno 2] No such file or directory: 'gamedata/kits.json'

**Comment by dkoz** [comment]
@iceyman You need to rename the `kits.json.example` to `kits.json`
